url: https://judithjanssen.es
baseurl: ''

# Site settings
name: Judith Janssen
title: 'health & wellness through yoga and movement'
logo: "/img/firma-judith-janssen.png"
email: judithjanssen@gmail.com
description: "health & wellness through yoga and movement: events, workshops & retreats"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  pages:
    output: true

# Default values
defaults:
  -
    scope: 
      path: ""
    values:
      layout: "page"
      lang: "en"
      navbar: true
      logo: true
      section: sitewide
      class: page
      image: /img/unsplash/blurred_lines.jpg
      newsletter:
        heading: Feel inspired?
        subheading: "I'm in the middle of preparing <strong>a meditation challenge</strong> and my new acts of love series.<br/><strong>Suscribe</strong> to my newsletter to stay tuned! No spam, I promise."
        field: Email
        button: Inspire me
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: "nl"
    values:
      lang: "nl"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: blog-post
      description: 'thoughts on health, wellness, yoga and movement'

