url: https://judithjanssen.es
baseurl: ''

# Site settings
title: Judith Janssen
logo: "/img/firma-judith-janssen.png"
email: judithjanssen@gmail.com
description: "4-day body-mind centering retreat by the mediterranean sea"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/judith.janssen.14
  - title: twitter
    url: https://twitter.com/judithjanssen_
  - title: linkedin
    url: https://www.linkedin.com/in/judithjanssen
  - title: envelope
    url: mailto:judithjanssen@gmail.com

# Build settings
markdown: kramdown
permalink: pretty

# Default values
defaults:
  -
    scope: 
      path: ""
    values:
      layout: "default"
      lang: "en"
      navbar: true
      logo: true
      section: sitewide
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: "nl"
    values:
      lang: "nl"